title: ZenAutofac
description: "Bridge library to use Autofac in a Zenject-like style"
url: "https://ileha.github.io"
baseurl: "/ZenAutofac"
github:
    zip_url: https://github.com/ileha/ZenAutofac/archive/refs/heads/main.zip
    repository_url: https://github.com/ileha/ZenAutofac
    tar_url: https://github.com/ileha/ZenAutofac/archive/refs/heads/main.tar.gz
logo: "{{ site.baseurl }}/icon.png"

show_downloads: true

remote_theme: pages-themes/cayman@v0.2.0

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-remote-theme

markdown: kramdown
kramdown:
    input: GFM
permalink: pretty

exclude:
    - .github/
    - .gitignore
    - .idea/
    - .vs/
    - nupkgs/
    - Tests/
    - ZenAutofac/
    - ZenAutofac.sln
    - ZenAutofac.sln.*

defaults:
    - scope:
          path: ""
      values:
          layout: "default"
